baseurl = "https://atmosmps.github.io/"
title = "Atmos Maciel"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "atmosmaciel"

# Enabling this option to allow rendering of HTML within Markdown files.
[markup.goldmark.renderer]
unsafe = true

[params]
    author = "Atmos Maciel"
    description = "I think you know what the problem is just as well as I do."
    keywords = "technology, developer, science, books, music, astronomy, runnig, fight"
    info = "Full Stack Developer"
    avatarurl = "images/avatar.png"
    footercontent = "I think you know what the problem is just as well as I do."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/custom.css"]
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/atmosmps/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/atmosmps/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/atmosmps/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/atmosmps/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@atmosmps"

[[params.social]]
    name = "Dev"
    icon = "fab fa-dev"
    weight = 5
    url = "https://dev.to/atmosmps"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            #[[languages.en.menu.main]]
            #name = "Projects"
            #weight = 3
            #url = "projects/"

            #[[languages.en.menu.main]]
            #name = "Contact me"
            #weight = 5
            #url = "contact/"

    [languages.pt-br]
        languagename = "Português"
        title = "Atmos Maciel"

        [languages.pt-br.params]
            author = "Atmos Maciel"
            info = "Desenvolvedor Full Stack"
            description = "I think you know what the problem is just as well as I do."
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "I think you know what the problem is just as well as I do."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            #[[languages.pt-br.menu.main]]
            #name = "Projetos"
            #weight = 3
            #url = "projects/"

            #[[languages.pt-br.menu.main]]
            #name = "Contato"
            #weight = 5
            #url = "contact/"
